name: 'Review Submission'
description: 'review open-source compliance on GitHub repositories'
inputs:
  url:
    description: 'GitHub repository URL'
    required: true
  token:
    description: 'GitHub access token'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
